# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Matthew\Documents\GitHub\FeedMe\src\pages\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FeedMe(object):
    def setupUi(self, FeedMe):
        FeedMe.setObjectName("FeedMe")
        FeedMe.resize(800, 585)
        FeedMe.setMinimumSize(QtCore.QSize(500, 585))
        self.centralwidget = QtWidgets.QWidget(FeedMe)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainWindowStack = QtWidgets.QStackedWidget(self.centralwidget)
        self.mainWindowStack.setObjectName("mainWindowStack")
        self.searchTab = QtWidgets.QWidget()
        self.searchTab.setObjectName("searchTab")
        self.searchPage = QtWidgets.QWidget(self.searchTab)
        self.searchPage.setGeometry(QtCore.QRect(0, 0, 782, 571))
        self.searchPage.setMinimumSize(QtCore.QSize(781, 571))
        self.searchPage.setObjectName("searchPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.searchPage)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchNameLabel = QtWidgets.QLabel(self.searchPage)
        self.searchNameLabel.setMaximumSize(QtCore.QSize(763, 33))
        font = QtGui.QFont()
        font.setFamily("Source Sans 3")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.searchNameLabel.setFont(font)
        self.searchNameLabel.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.searchNameLabel.setIndent(9)
        self.searchNameLabel.setObjectName("searchNameLabel")
        self.verticalLayout_3.addWidget(self.searchNameLabel)
        self.searchSearchBar = QtWidgets.QWidget(self.searchPage)
        self.searchSearchBar.setMinimumSize(QtCore.QSize(197, 58))
        self.searchSearchBar.setObjectName("searchSearchBar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.searchSearchBar)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.searchSearchBar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(171, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet(
            "background-color: rgba(255, 255, 255, 255); border: 1px hidden; border-radius:18px;"
        )
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.searchSearchBar)
        self.searchListWidget = QtWidgets.QWidget(self.searchPage)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.searchListWidget.sizePolicy().hasHeightForWidth()
        )
        self.searchListWidget.setSizePolicy(sizePolicy)
        self.searchListWidget.setMinimumSize(QtCore.QSize(500, 449))
        self.searchListWidget.setObjectName("searchListWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.searchListWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchListView = QtWidgets.QListView(self.searchListWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.searchListView.sizePolicy().hasHeightForWidth()
        )
        self.searchListView.setSizePolicy(sizePolicy)
        self.searchListView.setMinimumSize(QtCore.QSize(743, 431))
        self.searchListView.setStyleSheet(
            "background-color: rgba(255, 255, 255, 255); border: 1px hidden; border-radius: 20px;"
        )
        self.searchListView.setObjectName("searchListView")
        self.verticalLayout.addWidget(self.searchListView)
        self.verticalLayout_3.addWidget(self.searchListWidget)
        self.mainWindowStack.addWidget(self.searchTab)
        self.shoppingListTab = QtWidgets.QWidget()
        self.shoppingListTab.setObjectName("shoppingListTab")
        self.shoppingPage = QtWidgets.QWidget(self.shoppingListTab)
        self.shoppingPage.setGeometry(QtCore.QRect(0, 0, 782, 571))
        self.shoppingPage.setMinimumSize(QtCore.QSize(781, 571))
        self.shoppingPage.setObjectName("shoppingPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.shoppingPage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.shoppingNameLabel = QtWidgets.QLabel(self.shoppingPage)
        self.shoppingNameLabel.setEnabled(True)
        self.shoppingNameLabel.setMaximumSize(QtCore.QSize(763, 33))
        font = QtGui.QFont()
        font.setFamily("Source Sans 3")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.shoppingNameLabel.setFont(font)
        self.shoppingNameLabel.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.shoppingNameLabel.setIndent(9)
        self.shoppingNameLabel.setObjectName("shoppingNameLabel")
        self.verticalLayout_5.addWidget(self.shoppingNameLabel)
        self.shoppingListWidget = QtWidgets.QWidget(self.shoppingPage)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.shoppingListWidget.sizePolicy().hasHeightForWidth()
        )
        self.shoppingListWidget.setSizePolicy(sizePolicy)
        self.shoppingListWidget.setMinimumSize(QtCore.QSize(500, 449))
        self.shoppingListWidget.setObjectName("shoppingListWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.shoppingListWidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.shoppingListView = QtWidgets.QListView(self.shoppingListWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.shoppingListView.sizePolicy().hasHeightForWidth()
        )
        self.shoppingListView.setSizePolicy(sizePolicy)
        self.shoppingListView.setMinimumSize(QtCore.QSize(743, 431))
        self.shoppingListView.setStyleSheet(
            "background-color: rgba(255, 255, 255, 255); border: 1px hidden; border-radius: 20px;"
        )
        self.shoppingListView.setProperty("isWrapping", False)
        self.shoppingListView.setViewMode(QtWidgets.QListView.ListMode)
        self.shoppingListView.setObjectName("shoppingListView")
        self.verticalLayout_7.addWidget(self.shoppingListView)
        self.verticalLayout_5.addWidget(self.shoppingListWidget)
        self.mainWindowStack.addWidget(self.shoppingListTab)
        self.verticalLayout_2.addWidget(self.mainWindowStack)
        FeedMe.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FeedMe)
        self.statusbar.setObjectName("statusbar")
        FeedMe.setStatusBar(self.statusbar)

        self.retranslateUi(FeedMe)
        self.mainWindowStack.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(FeedMe)

    def retranslateUi(self, FeedMe):
        _translate = QtCore.QCoreApplication.translate
        FeedMe.setWindowTitle(_translate("FeedMe", "Feed Me"))
        self.searchNameLabel.setText(_translate("FeedMe", "Food Search"))
        self.lineEdit.setPlaceholderText(_translate("FeedMe", "🔍 Search"))
        self.shoppingNameLabel.setText(_translate("FeedMe", "Shopping List"))


import resources_rc
