# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Matthew\Documents\GitHub\FeedMe\src\pages\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FeedMe(object):
    def setupUi(self, FeedMe):
        FeedMe.setObjectName("FeedMe")
        FeedMe.resize(800, 585)
        FeedMe.setMinimumSize(QtCore.QSize(500, 585))
        self.centralwidget = QtWidgets.QWidget(FeedMe)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchPage = QtWidgets.QWidget(self.centralwidget)
        self.searchPage.setMinimumSize(QtCore.QSize(781, 571))
        self.searchPage.setObjectName("searchPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.searchPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pageNameLabel = QtWidgets.QLabel(self.searchPage)
        self.pageNameLabel.setMaximumSize(QtCore.QSize(763, 33))
        font = QtGui.QFont()
        font.setFamily("Source Sans 3")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pageNameLabel.setFont(font)
        self.pageNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pageNameLabel.setIndent(9)
        self.pageNameLabel.setObjectName("pageNameLabel")
        self.verticalLayout_3.addWidget(self.pageNameLabel)
        self.searchBar = QtWidgets.QWidget(self.searchPage)
        self.searchBar.setMinimumSize(QtCore.QSize(197, 58))
        self.searchBar.setObjectName("searchBar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.searchBar)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.searchBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(171, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgba(255, 255, 255); border: 1px hidden; border-radius:18px;")
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.searchBar)
        self.listWidget = QtWidgets.QWidget(self.searchPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(500, 449))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.listWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(self.listWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setMinimumSize(QtCore.QSize(743, 431))
        self.listView.setStyleSheet("background-color: rgba(255, 255, 255); border: 1px hidden; border-radius: 20px;")
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.verticalLayout_3.addWidget(self.listWidget)
        self.verticalLayout_2.addWidget(self.searchPage)
        FeedMe.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FeedMe)
        self.statusbar.setObjectName("statusbar")
        FeedMe.setStatusBar(self.statusbar)

        self.retranslateUi(FeedMe)
        QtCore.QMetaObject.connectSlotsByName(FeedMe)

    def retranslateUi(self, FeedMe):
        _translate = QtCore.QCoreApplication.translate
        FeedMe.setWindowTitle(_translate("FeedMe", "Feed Me"))
        self.pageNameLabel.setText(_translate("FeedMe", "Food Search"))
        self.lineEdit.setPlaceholderText(_translate("FeedMe", "🔍 Search"))
import resources_rc
